language: node_js
os: linux
cache: yarn
install:
  - yarn install
script:
  - yarn build
before_deploy:
  - cd bin && zip -r ../extension.zip . && cd ..
  - export RELEASES_TAG_NAME=v$(jq -r .version src/manifest.json)
  - export RELEASES_RELEASE_NOTES=$TRAVIS_COMMIT_MESSAGE
  - export RELEASES_TARGET_COMMITISH=$TRAVIS_COMMIT
  - git config --local user.name "iamtheyammerdeploy"
  - git config --local user.email "65838519+iamtheyammerdeploy@users.noreply.github.com"
  - git tag $RELEASES_TAG_NAME
deploy:
  provider: releases
  user: iamtheyammerdeploy
  file: extension.zip
  draft: true
  edge: true
  on:
    branch: master
